### ISSUE TITLE
How to build web file?

### ISSUE THREAD

**Issue by fengxuway** [jmshrv/finamp#860]
I want to run finamp in browse, but run `flutter build web` got error: "Missing index.html", how to fix it?

**Comment by fengxuway** [comment]
Explain the use case.

I want to run finamp on Tesla's car. Although it does not support independent app installation, I hope to deploy a web container + finame on my home nas, so that I can access it on the car browser.

**Comment by fengxuway** [comment]
mark the steps.

first, add web platform support to the project, then build web
```
flutter create --platforms=web .

flutter build web
```

**Comment by fengxuway** [comment]
build got error: ` The method 'hashValues' isn't defined for the class 'SliverStickyHeaderState'`

two dependences lib must update `hashValues` function name to `Object.hash()` function. I fork it and fix:

add these dependence by git to file: `pubspec.yaml` - sectoin: `dependencies:`
```
  flutter_slidable:
    git:
      url: https://github.com/letsar/flutter_slidable.git
      ref: master
  flutter_sticky_header:
    git:
      url: https://github.com/fengxuway/flutter_sticky_header.git
      ref: test
  value_layout_builder:
    git:
      url: https://github.com/fengxuway/value_layout_builder.git
      ref: master
```
